- name: install and configure dispatch micro service
  hosts: dispatch
  become: yes
  vars:
    app_user: roboshop
    app_directory: /app
    zip_url: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
  tasks:
    - name: install go language
      ansible.builtin.dnf:
        name: golang
        state: present
    
    - name: create system user
      ansible.builtin.user:
        name: "{{ app_user }}"
        system: true
        home: "{{ app_directory }}"
        create_home: yes
        shell: /sbin/nologin
        
    - name: create application folder
      ansible.builtin.file:
        path: "{{ app_directory }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'

    - name: download the dispatch.zip file
      ansible.builtin.get_url:
        url: "{{ zip_url }}"
        dest: /tmp/dispatch.zip

    - name: extract the zip file
      ansible.builtin.unarchive:
        src: /tmp/dispatch.zip
        remote_src: yes
        dest: "{{ app_directory }}"
        creates: "{{ app_directory }}/main.go"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0644'

    - name: initialize the go module
      ansible.builtin.command: go mod init dispatch
      args:
        chdir: "{{ app_directory }}"
      ignore_errors: yes

    - name: download go dependencies
      ansible.builtin.command: go get
      args:
        chdir: "{{ app_directory }}"
    
    - name: build the go project
      ansible.builtin.command: go build
      args:
        chdir: "{{ app_directory }}"

    - name: deploy systemd file
      ansible.builtin.copy:
        src: dispatch.service.j2
        dest: /etc/systemd/system/dispatch.service
      notify:
        - Reload systemd
        - Restart service
      
  handlers:
    - name: Reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: yes

    - name: Restart service
      ansible.builtin.service:
        name: dispatch
        enabled: true
        state: restarted



    



  