[mongodb]
192.168.146.137 ansible_user=rootshyam ansible_become=yes

[redis]
192.168.146.144 ansible_user=rootshyam ansible_become=yes

[mysql]
192.168.146.138 ansible_user=rootshyam ansible_become=yes

[rabbitmq]
192.168.146.143 ansible_user=rootshyam ansible_become=yes

[catalogue]
192.168.146.148 ansible_user=rootshyam ansible_become=yes

[user]
192.168.146.149 ansible_user=rootshyam ansible_become=yes ansible_password=T1t@nEdge

[cart]
192.168.146.150 ansible_user=rootshyam ansible_become=yes ansible_password=T1t@nEdge
