[mongodb]
192.168.146.137 ansible_user=rootshyam ansible_become=yes

[redis]
192.168.146.144 ansible_user=rootshyam ansible_become=yes

[mysql]
192.168.146.138 ansible_user=rootshyam ansible_become=yes

[rabbitmq]
192.168.146.143 ansible_user=rootshyam ansible_become=yes
