- name: install and configure redis
  hosts: redis

  tasks:
    - name: disable default redis app stream
      ansible.builtin.dnf:
        name: redis
        state: disabled

    - name: enable redis 7
      ansible.builtin.dnf:
        name: redis:7
        state: enabled

    - name: install redis
      ansible.builtin.dnf:
        name: redis
        state: present

    - name: Allow Connections From All Hosts
      ansible.builtin.lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^bind\s+127\.0\.0\.1'
        line: 'bind 0.0.0.0'

    - name: enable and start the redis service
      ansible.builtin.service:
        name: redis
        enabled: true
        state: started





  